word_list = [
    'Science',
    'Maths',
    'English',
    'Repair',
    'Artificial Intelligence',
    'School',
    'Classroom',
    'Friends',
    'Van', 
    'Principal',
    'Teacher',
    'Students',
    'Textbooks',
    'Classwork',
    'Computer Science',
    'Social',
    'Tamil',
    'Biology',
    'Physics',
    'Examination',
    'Pencil',
    'Pen',
    'Eraser',
    'Sharpner',
    'Bag',
    'Bench',
    'Playground',
    'History',
    'Civics',
]